### ISSUE TITLE
Is there any way to use blueprint without custom css attributes (bp-layout)?

### ISSUE THREAD

**Issue by animeshchat** [blueprintui/blueprintui#29]
I'm trying to use blueprint with react, which doesn't allow custom attributes to be used. Is there anyway to use this with class names?

**Comment by coryrylan** [comment]
If you use the Sass src directly you can set the prefix value in the config to `data-bp-layout` instead of `bp-layout`. That should allow it to be used with react.  I am working on adding more selector customization in the near future. 

https://github.com/splintercode/blueprint-css/blob/master/src/_config.scss

**Comment by martin-braun** [comment]
For anybody having the same problem, here is how to compile it yourself with a custom attribute `data-bp` that will be accepted by React: 

```scss

@import "~blueprint-css/src/_config.scss";
$prefix: 'data-bp';
@import "~blueprint-css/src/_base.scss";
@import "~blueprint-css/src/_column-generator.scss";
@import "~blueprint-css/src/_grid.scss";
@import "~blueprint-css/src/_util.scss";
@import "~blueprint-css/src/_spacing.scss";
```

**Comment by acespace90** [comment]
What if I use `$prefix: 'class';` in order to avoid custom attribute and use standard `class` attr? are there any contraindications?

**Comment by samfairsupply** [comment]
@coryrylan Is there a particular reason you are using a custom css attribute? compared to just using `class`?
Is the desire to not conflict with with other libraries a higher priority than trying to align with web standards?

(This is assuming that using custom css attributes to do css styling is "non standard")
