### ISSUE TITLE
Semantic grid

### ISSUE THREAD

**Issue by mmjaeger** [blueprintui/blueprintui#3]
Hello
I was wondering whether you've planned to add some mixins so the grid could be used in a more semantic unobtrusive way.

Thanks

**Comment by coryrylan** [comment]
Yeah thats on my road map. Probably over the next month or so it will be going under a refactor before calling it 1.0

**Comment by jovan-ivezic** [comment]
Hello, 
I have one question about Blueprint CSS markup. 
Are the bp-layout attributes allowed in html?

**Comment by coryrylan** [comment]
@jovan-ivezic Great question! Yes it is functionally allowed to have custom HTML attributes. There are other tech that takes advantage of this like JS frameworks, Angular (`ng-*`), Aurelia (`attr.bind`) and Vue (`v-*`). 

However for it to be 100% html5 spec compliant/valid it is recommended to add a `data-` prefix to all custom attributes. This is so if a browser implements a new attribute with functionality it does not collide with a developers existing custom attribute. Many CSS and JS libs either prefix their attributes (ex: `bp-*`) to reduce this risk or recommend the `data-` prefix.

On my todo list for the library is to add a CSS selector to allow `data-bp-layout` so if you need 100% html5 spec compliance you can. If you need it now you can use the Sass source directly and override the prefix here:
https://github.com/splintercode/blueprint-css/blob/master/src/_config.scss#L4

You can find more docs about custom attributes here
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by jovan-ivezic** [comment]
@splintercode thank you. Framework is really great. Excellent work :+1:

**Comment by coryrylan** [comment]
@jovan-ivezic Thank you! :)
