### ISSUE TITLE
see if its possible to center individual columns

### ISSUE THREAD

**Issue by coryrylan** [blueprintui/blueprintui#33]

**Comment by Cassidie** [comment]
Any chance we can see this enhancement soon? We're needing to center a single column, and we're having trouble getting the offset to work.

**Comment by coryrylan** [comment]
So using the offset like the second example doesn't seem to work? https://blueprintcss.io/docs/column-centering

**Comment by Cassidie** [comment]
It doesn't work for one column, intuitively. What's the formula for figuring out the offset for a column?

**Comment by coryrylan** [comment]
Yeah agree it's not intuitive nor true centering. The offset works with CSS Grids `grid-column-start` so when we say `offset-5` we mean place the item at the start of the 5th column. So with this you can calculate what the center will be in some cases.

![screen shot 2019-01-23 at 2 56 15 pm](https://user-images.githubusercontent.com/2021067/51636681-74785080-1f1f-11e9-9d14-4add21a1d236.png)

True grid auto centering is something that I would like to work on but not sure when it will get done nor if possible. If its just a single block item then you can avoid the grid all together and just use the float center util https://blueprintcss.io/docs/util-floats

![screen shot 2019-01-23 at 3 01 26 pm](https://user-images.githubusercontent.com/2021067/51636816-c6b97180-1f1f-11e9-9ae1-cf1d9e487d01.png)

**Comment by Cassidie** [comment]
Thank you for the explanation! Yeah we found that float-center was the way to go, but I saw this issue and wanted more info since the docs mentioned the offset. :) Thanks again, Corito!
