### ISSUE TITLE
Docs: page horizontal scroll on Chrome on iOS

### ISSUE THREAD

**Issue by jimthedev** [blueprintui/blueprintui#4]
Hi there. On an iPhone 6 in Chrome the code blocks in the docs look like this and it pushes the body wider so you can horizontal scroll on the page (and not on the code blocks). Just figured you might want to know. ![image](https://cloud.githubusercontent.com/assets/108938/14193719/d4375256-f76c-11e5-91c9-751eb5889c81.png)

**Comment by coryrylan** [comment]
Thanks! Ill take a look and get it fixed.

**Comment by coryrylan** [comment]
Fixed
