### ISSUE TITLE
ignore div flag?

### ISSUE THREAD

**Issue by LukeHartcher** [blueprintui/blueprintui#44]
Is/Would it be possible to have a bp="ignore" (or something similar) so the parent div could be ignored from the responsiveness, but the child divs are still responsive?

An example case may be a div that is only used for a conditional show/hide container, but it is the child divs of that container that you need responsive. Currently they will not get responsive as the blueprint is only seeing the parent conditional container/div.

Or is there a workaround?

```
<div bp="grid 3">
	<div>responsive</div>
	<div>responsive</div>
	<div bp="ignore" class="my-conditional-container">
		<div>responsive</div>
		<div>responsive</div>
	</div>
</div>
```

**Comment by coryrylan** [comment]
Hmm that might be tricky, if you don't mind me asking what tech or how you are triggering that conditional? Ex vanillia JS, Vue, Angular, ect... Many frameworks allow a conditional in a template without having to render a placeholder element.

**Comment by LukeHartcher** [comment]
I did end up working around within Angular. Thanks!
