### ISSUE TITLE
IE fallback issue?

### ISSUE THREAD

**Issue by LukeHartcher** [blueprintui/blueprintui#58]
When using multiple grids on the same page IE is not closing the div correctly and hence the following grids are becoming indented.

If I change your cleafix code to use "display: table;" (as suggested here https://css-tricks.com/snippets/css/clear-fix/) it works.

Is this a change you would consider implementing?

(Disclaimer: I am by no means a CSS guru so will leave to your best judgement, but currently it appears broken).

Below is the overrides I have added to my own code to resolve:

```
/* ie blueprint clearfix fix override https://unpkg.com/blueprint-css@3.0.0/dist/fallback/blueprint.css */
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    [bp~='grid']::after {
        display: table !important;
    }
}
@supports not (display: grid) {
    [bp~='grid']::after {
        display: table !important;
    }
}
```

**Comment by SCPCOEXR** [comment]
@coryrylan I think you need to adjust the IE10+ CSS targeting.
`@media screen and (-ms-high-contrast: active), screen and (-ms-high-contrast: none) { styles }`
**Note the , screen and**

Can confirm that switching display to table works in IE11.

**Comment by coryrylan** [comment]
Closing as dropping support for IE in next major
