### ISSUE TITLE
flex-row--stretch specifies justify-content

### ISSUE THREAD

**Issue by pdf** [blueprintui/blueprintui#9]
`flex-row--stretch` specifies `justify-content` which makes it override the spacing classes due to its position in the file.

AIUI, `justify-content` should not be required for `align-items: stretch` to work, so I think it this may be fixed by just deleting `justify-content` from the `shrink` helper, unless there's a reason it's necessary, in which case, just reordering would allow the spacing classes to take precedence.

**Comment by coryrylan** [comment]
Thanks for filling the issue. I'll take a look today see if I can find a fix. 👍

**Comment by coryrylan** [comment]
Fixed, `justify-content` removed

**Comment by pdf** [comment]
Awesome, thank you for the rapid turn-around.
